title: "Swoft 2.x Docs"
remote_theme: pmarsceill/just-the-docs

color_scheme: "light"
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Swoft on GitHub":
    - "//github.com/swoft-cloud/swoft"
  "Swoft Docs Repo":
    - "//github.com/swoft-cloud/swoft-doc"


# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit on GitHub."
gh_edit_repository: "https://github.com/swoft-cloud/swoft-doc" # the github URL for your repo
gh_edit_branch: "2.x" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


